In [12]:
import pandas as pd

In [13]:
logs = pd.read_csv("../data/logs.csv")

logs

    user_id  login_count  failed_logins  traffic_mb  session_duration
0   USR-001            5              1         100                60
1   USR-002            6              0         120                55
2   USR-003            4              1          95                62
3   USR-004            5              0         110                58
4   USR-001            6              1         105                61
5   USR-002            5              0         115                57
6   USR-003            7              1         100                65
7   USR-004            4              0          90                54
8   USR-001            5              1          98                59
9   USR-002            6              0         125                56
10  USR-003            5              1         102                63
11  USR-004            6              0         108                60
12  USR-001          100             80        5000               900

In [14]:
features = [
    "login_count",
    "failed_logins",
    "traffic_mb",
    "session_duration"
]

X = logs[features]

X

    login_count  failed_logins  traffic_mb  session_duration
0             5              1         100                60
1             6              0         120                55
2             4              1          95                62
3             5              0         110                58
4             6              1         105                61
5             5              0         115                57
6             7              1         100                65
7             4              0          90                54
8             5              1          98                59
9             6              0         125                56
10            5              1         102                63
11            6              0         108                60
12          100             80        5000               900

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

X_scaled[:5]

array([[-0.30173112, -0.26500464, -0.29301224, -0.28492927],
       [-0.26210986, -0.31219725, -0.27767746, -0.30724301],
       [-0.34135238, -0.26500464, -0.29684594, -0.27600378],
       [-0.30173112, -0.31219725, -0.28534485, -0.29385477],
       [-0.26210986, -0.26500464, -0.28917855, -0.28046653]])

In [16]:
from sklearn.cluster import DBSCAN

dbscan = DBSCAN(
    eps=0.5,
    min_samples=5
)

In [17]:
labels = dbscan.fit_predict(X_scaled)

print(labels)

[ 0  0  0  0  0  0  0  0  0  0  0  0 -1]

In [18]:
logs["cluster"] = labels

logs

    user_id  login_count  failed_logins  traffic_mb  session_duration  cluster
0   USR-001            5              1         100                60        0
1   USR-002            6              0         120                55        0
2   USR-003            4              1          95                62        0
3   USR-004            5              0         110                58        0
4   USR-001            6              1         105                61        0
5   USR-002            5              0         115                57        0
6   USR-003            7              1         100                65        0
7   USR-004            4              0          90                54        0
8   USR-001            5              1          98                59        0
9   USR-002            6              0         125                56        0
10  USR-003            5              1         102                63        0
11  USR-004            6              0         108                60        0
12  USR-001          100             80        5000               900       -1

In [19]:
logs["is_anomaly"] = logs["cluster"] == -1

logs

,user_id,login_count,failed_logins,traffic_mb,session_duration,cluster,is_anomaly
0,USR-001,5,1,100,60,0,False
1,USR-002,6,0,120,55,0,False
2,USR-003,4,1,95,62,0,False
3,USR-004,5,0,110,58,0,False
4,USR-001,6,1,105,61,0,False
5,USR-002,5,0,115,57,0,False
6,USR-003,7,1,100,65,0,False
7,USR-004,4,0,90,54,0,False
8,USR-001,5,1,98,59,0,False
9,USR-002,6,0,125,56,0,False
10,USR-003,5,1,102,63,0,False
11,USR-004,6,0,108,60,0,False
12,USR-001,100,80,5000,900,-1,True

In [20]:
logs[logs["is_anomaly"]]

,user_id,login_count,failed_logins,traffic_mb,session_duration,cluster,is_anomaly
12,USR-001,100,80,5000,900,-1,True

In [21]:
print("Number of anomalies:", logs["is_anomaly"].sum())

Number of anomalies: 1